# This file is part of project link.developers/ld-node-novatel-gnss-ins-2.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://gitlab.com/link.developers/ld-node-novatel-gnss-ins-2.
#
# SPDX-License-Identifier: MPL-2.0

package:
  name: "ld-node-novatel-gnss-ins-2"
  version: {{ BUILD_VERSION }}

source:
  git_url: ../

requirements:
  build:
    skip: true  # [not x86_64]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ld-cmake-tools
    - flatc
    
  host:
    - link2-cpp
    - novatel >=0.9.0.1
    - serial
    - spdlog

  run:
    - link2
    - novatel >=0.9.0.1
    - serial

test:
  commands:
    - "ld-node-novatel-gnss-ins-2 --help"

extra:
  git-commit: {{ GIT_FULL_HASH }}

about:
  home: "https://gitlab.com/link.developers/ld-node-novatel-gnss-ins-2"
  license: "MPL-2.0"
  license_file: "LICENSE"
  summary: "An application to retrieve positional and inertial data from Novatel OEM4 and OEMV series of devices ideally suited for OEMV receivers equipped with SPAN technology."
