# This file is part of project link.developers/ld-node-novatel-gnss-ins-2.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://gitlab.com/link.developers/ld-node-novatel-gnss-ins-2.
#
# SPDX-License-Identifier: MPL-2.0

package:
  name: "ld-node-novatel-gnss-ins-2"
  version: {{ BUILD_VERSION }}

source:
  git_url: ../

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - novatel>0.9.0
    - serial
    - boost
    - ld-data-protobuf
    - ld-cmake-tools
    - ld-lib-geospatial
    - flatc
    - spdlog

  host:
    - link2-cpp
    - ld-lib-geospatial

  run:
    - novatel>0.9.0
    - serial
    - ld-data-protobuf
    - link2
    - boost

test:
  commands:
    - "ld-node-novatel-gnss-ins-2 --help"
    - novatel>0.9.0
    - serial
    - ld-data-protobuf
    - link
    - boost

extra:
  git-commit: {{ GIT_FULL_HASH }}

about:
  home: "https://gitlab.com/link.developers/ld-node-novatel-gnss-ins-2"
  license: "MPL-2.0"
  license_file: "LICENSE"
  summary: "An application to retrieve positional and inertial data from Novatel OEM4 and OEMV series of devices ideally suited for OEMV receivers equipped with SPAN technology."

